services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: melodev
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: initdb
    volumes:
      - postgres_data:/var/lib/postgresql@16/data
      - ./init:/docker-entrypoint-initdb.d/

volumes:
  postgres_data: